### ISSUE TITLE
Difficulties in getting your TAP environment fully working

### ISSUE THREAD

**Issue by Analect** [halkyonio/tap#13]
@cmoulliard, thanks for your work on this:

I was having trouble running your script/install.sh in one go, so I ran as far as here .. for installing the preliminary set of tools.
https://github.com/halkyonio/tap/blob/main/scripts/install.sh#L215

At https://github.com/halkyonio/tap/blob/main/scripts/install.sh#L165, I was having trouble with the env variables getting passed through to that other install.sh script .. so I think I had to modify slightly to `. ./install.sh -y`

I ended up running the imgpkg copy manually, rather than your https://github.com/halkyonio/tap/blob/main/scripts/install.sh#L217-L225 ... 
since I didn't want to start paying fees to host images on my ghcr.io and this 15GB of images would have taken me over my quota.

So ran this to copy to my own harbor (that harbor.xxxx.com won't be accessible to you though, as it's running locally, although has letsencrypt certs etc)
`imgpkg copy -b registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.1.1 --to-repo harbor.xxxx.com/tanzu-tap-halkyonio/tap-packages`

I ended up replacing your reference to pivnet assets for `tanzu-application-platform` to 1.1.1 (from 1.1.0).

```
pivnet download-product-files --product-slug='tanzu-application-platform' --release-version='1.1.1' --product-file-id=1212839
pivnet download-product-files --product-slug='tanzu-application-platform' --release-version='1.1.0' --product-file-id=1190781
```

I'm not sure build-service images were handled in your script to copy across `tap-packages`, so I additionally ran these below to get those artifacts across.

```
imgpkg copy -b "registry.tanzu.vmware.com/build-service/bundle:1.5.1" --to-repo harbor.xxxx.com/tanzu-tap-halkyonio/build-service
imgpkg copy -b registry.tanzu.vmware.com/tbs-dependencies/lite:100.0.307 --to-repo harbor.xxxx.com/tanzu-tap-halkyonio/tbs-dependencies
```

By the way, all EULAs were accepted.

I changed references below to point to my own harbor instance.
https://github.com/halkyonio/tap/blob/main/scripts/install.sh#L252-L254

While adding the tap repository and installing packages worked OK, neither `buildservice`, `cnrs` nor `tap` packages would ever reconcile.  As per error at the bottom of image below (in green) ... the `buildservice` image complains about x509 certificate has expired or is not yet valid. I'm somehow able to manually pull that image with docker using `docker pull registry.tanzu.vmware.com/tbs-dependencies/tap-1.1-lite:100.0.307` ... but maybe there some issue with docker-in-docker (associated with the `kind` I'm using to run-up a TCE unmanaged-cluster) that is prompting this certificate problem.

`tanzu package install tap -p tap.tanzu.vmware.com -v 1.1.1 --values-file tap-values.yml -n tap-install`

![image](https://user-images.githubusercontent.com/4063815/171005247-0ebeea47-bef8-4cb8-ae73-837f84d55562.png)

Given my certificate problem in getting tbs-dependencies from registry.tanzu.vmware.com, I thought I would try to install the build-service directly (as opposed through its inclusion in the tap-package).

I tried these, based on TAP docs, which avoids kapp-controller and rather relies on the kapp cli directly:
```
imgpkg pull -b harbor.xxxx.com/tanzu-tap-halkyonio/build-service:1.5.1 -o /tmp/bundle

ytt -f /tmp/bundle/config/ \
	-v kp_default_repository='harbor.xxxx.com/tanzu-tap-halkyonio/build-service' \
	-v kp_default_repository_username='xxx' \
	-v kp_default_repository_password='xxxx' \
	--data-value-yaml pull_from_kp_default_repo=true \
	-v tanzunet_username='xxxx' \
	-v tanzunet_password='xxxx' \
	-v descriptor_name='lite' \
	--data-value-yaml enable_automatic_dependency_updates=true \
	| kbld -f /tmp/bundle/.imgpkg/images.yml -f- \
	| kapp deploy -a tanzu-build-service -f- -y
```

... and ..

```
imgpkg pull -b harbor.xxxx.com/tanzu-tap-halkyonio/tbs-dependencies:100.0.307 -o /tmp/descriptor-bundle
kbld -f /tmp/descriptor-bundle/.imgpkg/images.yml \
   -f /tmp/descriptor-bundle/tanzu.descriptor.v1alpha3/lite-descriptor-100.0.307.yaml \
   | kp import -f -
```
However, that failed to fix things ... there were conflicting assets in different namespaces ... and so forth.

![Image](https://user-images.githubusercontent.com/4063815/170966076-ad5476d2-36c7-4804-88fb-3c610f6e502a.png)
![Image](https://user-images.githubusercontent.com/4063815/170966194-b9dbdef9-8406-4571-8999-ee2e3b225358.png)

I think I may have also tried to install the buildservice with the tanzu CLI too, but to no avail.

```
tanzu package install buildservice -p buildservice.tanzu.vmware.com -v 1.5.1 -n tap-install -f tbs-values.yaml --poll-timeout 30m
tanzu package installed update buildservice -p buildservice.tanzu.vmware.com -v 1.5.1 -n tap-install -f tbs-values.yaml --poll-timeout 30m
```

**Comment by cmoulliard** [comment]
> I was having trouble running your script/install.sh in one go, so I ran as far as here .. for installing the preliminary set of tools.
> https://github.com/halkyonio/tap/blob/main/scripts/install.sh#L215

What is the problem that you have here ?

**Comment by cmoulliard** [comment]
> At https://github.com/halkyonio/tap/blob/main/scripts/install.sh#L165, I was having trouble with the env variables getting passed through to that other install.sh script .. so I think I had to modify slightly to `. ./install.sh -y`

I do this to pass the env vars when I execute the script remotely. Does that help ?
```
ssh -i ${SSH_KEY} ${USER}@${IP} -p ${PORT} \
    REMOTE_HOME_DIR="/home/centos" \
    VM_IP=${IP} \
    REGISTRY_SERVER="ghcr.io" \
    REGISTRY_OWNER="halkyonio" \
    REGISTRY_USERNAME="xxxxxx" \
    REGISTRY_PASSWORD="yyyyyyyyy" \
    TANZU_REG_SERVER="registry.tanzu.vmware.com" \
    TANZU_REG_USERNAME="cmoulliard@redhat.com" \
    TANZU_REG_PASSWORD="xxxxxxxxx" \
    TANZU_PIVNET_LEGACY_API_TOKEN="xxxxxxxxxxx" \
    COPY_PACKAGES="false" \
    "bash -s" -- < ./scripts/install.sh
```

**Comment by cmoulliard** [comment]
> I ended up replacing your reference to pivnet assets for `tanzu-application-platform` to 1.1.1 (from 1.1.0).
> 
> ```
> pivnet download-product-files --product-slug='tanzu-application-platform' --release-version='1.1.1' --product-file-id=1212839
> pivnet download-product-files --product-slug='tanzu-application-platform' --release-version='1.1.0' --product-file-id=1190781
> ```

Do we have to bump 1.1.0 to 1.1.1 for the following properties ?
https://github.com/halkyonio/tap/blob/tap-v1.1.0/scripts/install.sh#L86-L88

**Comment by Analect** [comment]
> Do we have to bump 1.1.0 to 1.1.1 for the following properties ?

TANZU_CLUSTER_ESSENTIALS_VERSION="1.1.0"  ... still at 1.1.0 ... see [here](https://network.pivotal.io/products/tanzu-cluster-essentials/ )
TAP_VERSION="1.1.1" ... moves to 1.1.1
TANZU_CLI_VERSION="v0.11.2" ... moves to v0.11.4 (I think)

> I do this to pass the env vars when I execute the script remotely. Does that help ?

I'm sure that helps .. I was just ssh'ing into the machine first and running the script from your repo cloned locally to that machine ... I think I ended up feeding all my variables on a single line (see below) ... since with line-breaks, things weren't working ... for me, at least.  Disregard my usage of `install_mod_postpivnet.sh` below ... it was just my way of avoiding going through all downloads over-and-over, while I tried to get package reconciliation to work.  I did notice that feeding a 'legacy-api-token' no longer worked for `pivnet`.  It somehow wanted the `UAA API TOKEN`.

```
REMOTE_HOME_DIR=/home/xxx/ VM_IP=192.168.192.13 REGISTRY_SERVER=harbor.xxxx.com REGISTRY_OWNER=tanzu-tap-halkyonio REGISTRY_USERNAME=xxxx REGISTRY_PASSWORD=xxxx TANZU_PIVNET_LEGACY_API_TOKEN="xxxx" TANZU_REG_SERVER=registry.tanzu.vmware.com TANZU_REG_USERNAME=xxxx TANZU_REG_PASSWORD=xxx ./install_mod_postpivnet.sh
```

**Comment by cmoulliard** [comment]
> Disregard my usage of `install_mod_postpivnet.sh` below ..

PR are welcome by the way ;-)

**Comment by cmoulliard** [comment]
> I ended up running the imgpkg copy manually, rather than your https://github.com/halkyonio/tap/blob/main/scripts/install.sh#L217-L225 ...
> since I didn't want to start paying fees to host images on my ghcr.io and this 15GB of images would have taken me over my quota.

You should be able to copy the images from Tanzu registry to your local harbor registry if you set the following parameters of the bash script instead of using docker.io, ghcr.io, ...:
```
REGISTRY_SERVER => local harbor instance
REGISTRY_OWNER => harbor project
```

**Comment by cmoulliard** [comment]
> about x509 certificate has expired or is not yet valid.

hmhmh. It seems that during the installation of TBS, it tries to download the image from `registry.tanzu.vmware.com/tbs-dependencies/tap-1.1-lite:100.0.307` instead of your local image which should start with `harbor.xxxx`. I will try to install harbor this week to reproduce your issue.
Did you check this doc chapter - https://docs.vmware.com/en/Tanzu-Application-Platform/1.1/tap/GUID-tanzu-build-service-install-tbs.html#install-tanzu-build-service-using-the-tanzu-cli-airgapped-2 ?

**Comment by cmoulliard** [comment]
> to my own harbor

How did you installed it as by default TAP do not install it ? Which instructions did you followed to install it ?

**Comment by Analect** [comment]
> How did you installed it as by default TAP do not install it ? Which instructions did you followed to install it ?

The harbor I use is not in a kubernetes cluster.  I'm running the harbor on a separate VM based on the docker-compose approach here:  https://goharbor.io/docs/2.5.0/install-config/
I then use certbot to interact with letsencrypt for generating the various .crt and .key files, which get bound to the docker set-up via a ~/data/cert/ folder, as well as copied into the local docker /etc/docker/certs.d/ folder, so docker then trusts that local registry.

![image](https://user-images.githubusercontent.com/4063815/171153754-3d10184d-22d2-4b28-a9a0-7909c69e0f20.png)

> Have you set the ca_cert_data: CA-CERT-CONTENTS property as reported here

The output from generating letsencrypt certs are chain.pem, cert.pem and privkey.pem files.
To work with harbor, you copy the privkey.pem as harbor.key; combine cert.pem and chain.pem as the harbor.crt and copy the chain.pem as the ca.crt file ... somewhat along the lines of this mapping below.

![Image](https://user-images.githubusercontent.com/4063815/171149712-333fc4b5-182c-4dc0-b30a-47c3c7f5012c.png)

It is this latter ca.crt file that I'm using to feed the ca_cert_data field in `tap-values.yaml` .... or directly in a `tbs-values.yaml`, if I'm trying to install the build-service independently of TAP.

![image](https://user-images.githubusercontent.com/4063815/171149172-940be9c8-f1f9-4919-af53-2d4136e9f0bb.png)

I'm not sure that is necessarily the problem though.  I'm trying to understand why it's properly referencing/sourcing my local harbor for the build-service images ... but then it's reverting back to the pivotal registry for the dependencies ... it appears to automatically create a `TanzuNetDependencyUpdater` object.  When I was experimenting with directly installing TBS using kapp (ie. not kapp-controller from tap-values.yaml), even if I set this to false `--data-value-yaml enable_automatic_dependency_updates=false`, that still somehow created this `TanzuNetDependencyUpdater`, which would get stuck on this `x509: certificate has expired or is not yet valid` problem.

![image](https://user-images.githubusercontent.com/4063815/171151903-a8e31e16-4c03-48d4-8ff4-c27410317049.png)

**Comment by cmoulliard** [comment]
> I then use certbot to interact with letsencrypt for generating the various .crt and .key files, which get bound to the docker set-up via a ~/data/cert/ folder, as well as copied into the local docker /etc/docker/certs.d/ folder, so docker then trusts that local registry.

You do not need letsencrypt except if you need to expose the registry using a domain name. For local access, a selfsigned certificate could be generated and next shared

Something like
```
create_openssl_cfg() {
CFG=$(cat <<EOF
[req]
distinguished_name = subject
x509_extensions    = x509_ext
prompt             = no
[subject]
C  = BE
ST = Namur
L  = Florennes
O  = Red Hat
OU = Snowdrop
CN = "harbor.$IP_AND_DOMAIN_NAME"
[x509_ext]
basicConstraints        = critical, CA:TRUE
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always, issuer:always
keyUsage                = critical, cRLSign, digitalSignature, keyCertSign
nsComment               = "OpenSSL Generated Certificate"
subjectAltName          = @alt_names
[alt_names]
DNS.1 = "harbor.$IP_AND_DOMAIN_NAME"
DNS.2 = "notary.$IP_AND_DOMAIN_NAME"
EOF
)
echo "$CFG"
}

log "CYAN" "Populate a self signed certificate ..."
mkdir -p $TMP_DIR/certs/harbor.$IP_AND_DOMAIN_NAME

log "CYAN" "Generate the openssl stuff"
create_openssl_cfg > $TMP_DIR/certs/req.cnf

log "CYAN" "Create the self signed certificate certificate and client key files"
openssl req -x509 \
  -nodes \
  -days 365 \
  -newkey rsa:4096 \
  -keyout $TMP_DIR/certs/harbor.${IP_AND_DOMAIN_NAME}/tls.key \
  -out $TMP_DIR/certs/harbor.${IP_AND_DOMAIN_NAME}/tls.crt \
  -config $TMP_DIR/certs/req.cnf \
  -sha256

#log_line "CYAN" "Copy the tls.crt under /usr/local/share/ca-certificates/harbor.$VM_IP.nip.io.crt and update the the ca-certificates"
log_line "CYAN" "Copy the tls.crt to /etc/pki/ca-trust/source/anchors/ and trust the certificate"
sudo cp $TMP_DIR/certs/harbor.${IP_AND_DOMAIN_NAME}/tls.crt /etc/pki/ca-trust/source/anchors/harbor.${IP_AND_DOMAIN_NAME}.crt
sudo update-ca-trust

log_line "CYAN" "Copy the tls.crt to /etc/docker/certs.d/harbor.${IP_AND_DOMAIN_NAME} and restart docker daemon"
sudo mkdir -p /etc/docker/certs.d/harbor.${IP_AND_DOMAIN_NAME}
sudo cp $TMP_DIR/certs/harbor.${IP_AND_DOMAIN_NAME}/tls.crt /etc/docker/certs.d/harbor.${IP_AND_DOMAIN_NAME}/ca.crt
sudo systemctl restart docker
```

**Comment by cmoulliard** [comment]
Can we close it or do we still have to document something, improve some bash scripts, ... ? @Analect
